version: '3.8'

services:
  lanchat:
    image: ghcr.io/yeongpin/lan-chat:main
    ports:
      - "${SERVER_PORT:-13050}:13050"
    env_file:
      - .env
    environment:
      - SERVER_PORT=${SERVER_PORT:-13050}
      - HOST=${HOST:-0.0.0.0}
      - VITE_SERVER_PORT=${VITE_SERVER_PORT:-13050}
      - VITE_NAME_LIMIT=${VITE_NAME_LIMIT:-20}
      - VITE_MESSAGE_SALT=your-custom-secret-salt-key
      - CLEANUP_INTERVAL=${CLEANUP_INTERVAL:-1h}
      - HISTORY_RETENTION=${HISTORY_RETENTION:-7d}
      - UPLOADS_RETENTION=${UPLOADS_RETENTION:-1d}
    volumes:
      - uploads:/app/server/uploads
      - ./dist:/app/dist
      - ./server:/app/server
      - ./.env.example:/app/.env

volumes:
  uploads: 