version: '3.8'

services:
  lanchat:
    image: ghcr.io/yeongpin/lan-chat:main
    ports:
      - "13050:13050"
      - "5173:5173"
    env_file:
      - .env.example
    environment:
      - SERVER_PORT=13050
      - HOST=0.0.0.0
      - PUBLIC_PORT=5173
      - PUBLIC_HOST=0.0.0.0
      - VITE_NAME_LIMIT=${VITE_NAME_LIMIT:-20}
      - VITE_MESSAGE_SALT=${VITE_MESSAGE_SALT:-your-secret-salt-key-here}
      - CLEANUP_INTERVAL=${CLEANUP_INTERVAL:-1h}
      - HISTORY_RETENTION=${HISTORY_RETENTION:-7d}
      - UPLOADS_RETENTION=${UPLOADS_RETENTION:-1d}
    volumes:
      - uploads:/app/server/uploads
    networks:
      - lanchat-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  uploads:

networks:
  lanchat-network:
    driver: bridge 