version: '3.8'

services:
  lanchat:
    build: .
    ports:
      - "${SERVER_PORT:-13050}:13050"
    env_file:
      - .env.example
    environment:
      - SERVER_PORT=${SERVER_PORT:-13050}
      - HOST=${HOST:-0.0.0.0}
      - VITE_SERVER_PORT=${VITE_SERVER_PORT:-13050}
      - VITE_NAME_LIMIT=${VITE_NAME_LIMIT:-20}
      - VITE_MESSAGE_SALT=${VITE_MESSAGE_SALT:-your-secret-salt-key-here}
      - CLEANUP_INTERVAL=${CLEANUP_INTERVAL:-1h}
      - HISTORY_RETENTION=${HISTORY_RETENTION:-7d}
      - UPLOADS_RETENTION=${UPLOADS_RETENTION:-1d}
    volumes:
      - uploads:/app/server/uploads

volumes:
  uploads: 